FROM nginx:alpine
RUN apk add --no-cache apache2-utils bash
COPY nginx.conf /etc/nginx/nginx.conf
CMD bash -lc 'htpasswd -bc /etc/nginx/.htpasswd "$BASIC_AUTH_USER" "$BASIC_AUTH_PASS" && exec nginx -g "daemon off;"'
