name: Rollback Staging

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/staging-github-oidc

  # Backend remoto de Terraform (deben existir en el Environment "staging")
  TF_BACKEND_BUCKET: ${{ secrets.AWS_ACCOUNT_ID }}-${{ vars.GH_REPO }}-staging
  TF_BACKEND_KEY: ${{ vars.GH_REPO }}/staging/terraform.tfstate 
  TF_BACKEND_DDB_TABLE: tf-locks-${{ vars.GH_REPO }}-staging

  # Variables Terraform (mismo prefijo/parametrización que el deploy)
  TF_VAR_gh_owner: ${{ vars.GH_OWNER }}
  TF_VAR_gh_repo:  ${{ vars.GH_REPO }}
  TF_VAR_name_prefix: staging

jobs:
  destroy:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sanitize any pre-set AWS creds
        shell: bash
        run: |
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE AWS_DEFAULT_PROFILE

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Assert OIDC creds
        shell: bash
        run: aws sts get-caller-identity

      # Asegura que existan bucket y tabla del backend (maneja us-east-1)
      - name: Ensure S3 bucket and DynamoDB table for tfstate
        shell: bash
        run: |
          set -euo pipefail
          echo "Region: $AWS_REGION"
          echo "Bucket: $TF_BACKEND_BUCKET"
          echo "DDB   : $TF_BACKEND_DDB_TABLE"

          if aws s3api head-bucket --bucket "$TF_BACKEND_BUCKET" 2>/dev/null; then
            echo "Bucket exists"
          else
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$TF_BACKEND_BUCKET"
            else
              aws s3api create-bucket \
                --bucket "$TF_BACKEND_BUCKET" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          fi

          aws s3api put-bucket-versioning \
            --bucket "$TF_BACKEND_BUCKET" \
            --versioning-configuration Status=Enabled

          aws s3api put-bucket-encryption \
            --bucket "$TF_BACKEND_BUCKET" \
            --server-side-encryption-configuration '{
              "Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]
            }'

          if aws dynamodb describe-table --table-name "$TF_BACKEND_DDB_TABLE" >/dev/null 2>&1; then
            echo "DynamoDB table exists"
          else
            aws dynamodb create-table \
              --table-name "$TF_BACKEND_DDB_TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # ⚠️ Terraform debe apuntar al backend S3 (el mismo que usó el deploy)
      - name: Terraform Init (S3 backend)
        working-directory: ./infrastructure
        run: |
          terraform init -input=fals
