name: Rollback Staging (manual)

on:
  workflow_dispatch: {}

jobs:
  call-reusable:
    environment: staging
    uses: ./cicd/rollback.yml
    with:
      AWS_REGION: ${{ vars.AWS_REGION }}
      GH_OWNER:   ${{ vars.GH_OWNER }}
      GH_REPO:    ${{ vars.GH_REPO }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
