name: Rollback Staging

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/staging-github-oidc

  TF_BACKEND_BUCKET: ${{ secrets.AWS_ACCOUNT_ID }}-${{ vars.GH_REPO }}-staging
  TF_BACKEND_DDB_TABLE: tf-locks-${{ vars.GH_REPO }}-staging
  TF_BACKEND_KEY_RUNTIME:: ${{ vars.GH_REPO }}/staging/runtime.tfstate

  TF_VAR_region: ${{ vars.AWS_REGION }}
  TF_VAR_name_prefix: staging
  TF_VAR_gh_owner: ${{ vars.GH_OWNER }}
  TF_VAR_gh_repo:  ${{ vars.GH_REPO }}
  TF_VAR_tf_backend_bucket: ${{ vars.TF_BACKEND_BUCKET }}
  TF_VAR_tf_backend_ddb_table: ${{ vars.TF_BACKEND_DDB_TABLE }}

jobs:
  destroy:
    environment: staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Sanitize any pre-set AWS creds
        shell: bash
        run: |
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE AWS_DEFAULT_PROFILE

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          role-duration-seconds: 7200

      - name: Assert OIDC creds
        shell: bash
        run: |
          date -u
          aws sts get-caller-identity

      - name: Ensure S3 bucket and DynamoDB table for tfstate
        shell: bash
        run: |
          set -euo pipefail
          if aws s3api head-bucket --bucket "$TF_BACKEND_BUCKET" 2>/dev/null; then
            echo "Bucket OK"
          else
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$TF_BACKEND_BUCKET"
            else
              aws s3api create-bucket --bucket "$TF_BACKEND_BUCKET" \
                --region "$AWS_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          fi
          aws s3api put-bucket-versioning --bucket "$TF_BACKEND_BUCKET" \
            --versioning-configuration Status=Enabled
          aws s3api put-bucket-encryption --bucket "$TF_BACKEND_BUCKET" \
            --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
          aws dynamodb describe-table --table-name "$TF_BACKEND_DDB_TABLE" >/dev/null 2>&1 || \
            aws dynamodb create-table \
              --table-name "$TF_BACKEND_DDB_TABLE" \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init (runtime)
        working-directory: ./infrastructure/runtime
        shell: bash
        run: |
          set -euo pipefail
          if aws s3api head-object --bucket "${TF_BACKEND_BUCKET}" --key "${TF_BACKEND_KEY_RUNTIME}" >/dev/null 2>&1; then
            INIT_FLAGS="-reconfigure"
          elif [ -f "terraform.tfstate" ]; then
            INIT_FLAGS="-migrate-state"
          else
            INIT_FLAGS=""
          fi
          terraform init -input=false ${INIT_FLAGS} \
            -backend-config="bucket=${TF_BACKEND_BUCKET}" \
            -backend-config="key=${TF_BACKEND_KEY_RUNTIME}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DDB_TABLE}" \
            -backend-config="encrypt=true"

      - name: Show state (debug)
        working-directory: ./infrastructure/runtime
        run: terraform state list || true

      - name: Destroy runtime
        working-directory: ./infrastructure/runtime
        shell: bash
        run: |
          set -euo pipefail
          terraform destroy -auto-approve -input=false -parallelism=5 -lock-timeout=10m
